#!/bin/bash
ERROR_FILE="/tmp/docker-images-update.error"

# make sure that docker is running
DOCKER_INFO_OUTPUT=$(docker info 2> /dev/null | grep "Containers:" | awk '{print $1}')

if [ "$DOCKER_INFO_OUTPUT" != "Containers:" ]; then
    echo "Docker is not running, exiting"
    exit 1
fi

# get a list of docker images that are currently installed
IMAGES_WITH_TAGS=$(docker images | grep -v TAG | grep -v "<none>" | awk '{printf("%s:%s\n", $1, $2)}' | grep '/')

# run docker pull on all of the images
for IMAGE in $IMAGES_WITH_TAGS; do
  echo -e "Updating \033[1;32m$IMAGE\033[0m"
  docker pull $IMAGE 2>$ERROR_FILE
  if [ $? != 0 ]; then
    if [ "$(cat $ERROR_FILE | grep 'not exist')" != "" ]; then
      echo "WARNING: Docker image $IMAGE not found in repository, skipping"
    else
      echo "ERROR: docker pull failed on image - $IMAGE"
      exit 2
    fi
  fi
  echo
done

echo "Docker images are now up to date"
exit 0
