#!/bin/bash

FNAME="Archivos_$(date +'%d-%m-%Y').zip"
mkdir /tmp/msi_backup 2>/dev/null
rm "/tmp/msi_backup/$FNAME" 2>/dev/null

# notify-send -a 'MSI Backup' 'Info' 'Compressing "Archivos" in a ZIP file...'
zip -r "/tmp/msi_backup/$FNAME" /home/toni/Archivos -x '*.git/*' -x '*env/*' -x '*venv/*' -x '*node_modules*' -x '*dist/*' -x '*buildozer/*' -x '*__pycache__*' -x '*.cia' -x '*.3ds' -x '*.cci'

thunar /tmp/msi_backup & disown
firefox 'https://drive.google.com/' & disown
