#!/bin/bash

BLUE='\033[0;34m'
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if systemctl status docker.service | grep 'inactive' &>/dev/null ; then
    echo -e "${RED}Docker service is stopped${NC}"
    echo -e "${GREEN}Starting docker...${NC}\n"
    sudo systemctl start docker.service
else
    echo -e "${GREEN}Docker service is running${NC}\n"
fi

function cleanup() {
    docker compose -f '/home/toni/Archivos/home_lab/development/docker-compose.yml' down
    exit 0
}

trap cleanup EXIT

docker compose -f '/home/toni/Archivos/home_lab/development/docker-compose.yml' up -d

echo -e "\n${BLUE}Acestream running at: http://${LOCAL_IP}${NC}"
echo -e "\nPress [Ctrl-C] to stop acestream...\n"

while true; do
    sleep 10
done
