#!/usr/bin/python3
# -*- coding: utf-8 -*-

import subprocess
import time

if __name__ == '__main__':
    while True:
        subprocess.check_output('sudo apt update'.split(), shell=False)
        print('Waiting...')
        time.sleep(120)
